version: "3.1"

services:
  db:
    image: postgres
    container_name: lifomation-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  tika:
    image: logicalspark/docker-tikaserver
    container_name: tika-server
    ports:
      - "9998:9998"

  meilisearch:
    image: getmeili/meilisearch:v1.9
    container_name: meilisearch
    environment:
      MEILI_ENV: ${MEILLI_ENV}
    ports:
      - "7700:7700"
    # volumes:
    #   - ./meili_data:/meili_data

